airbyte_dbt_transformations:
  outputs:
    dev:
      dbname: airbyte
      host: localhost
      pass: airbyte
      port: 5431
      schema: airbyte
      threads: 1
      type: postgres
      user: airbyte
  target: dev
